### ISSUE TITLE
Buffer.allocUnsafe is not a function

### ISSUE THREAD

**Issue by Mellowz** [JoshGlazebrook/smart-buffer#18]
i got error when  "new SmartBuffer()"

`/root/cwproj/node_modules/smart-buffer/build/smartbuffer.js:54
            this._buff = Buffer.allocUnsafe(DEFAULT_SMARTBUFFER_SIZE);
                                ^

TypeError: Buffer.allocUnsafe is not a function
    at new SmartBuffer (/root/cwproj/node_modules/smart-buffer/src/smartbuffer.ts:67:27)
    at LoginAck.getData (/root/cwproj/network/send/login_ack.js:14:18)
    at Connection.sendData (/root/cwproj/network/connection.js:42:25)
    at Login.process (/root/cwproj/network/recv/login.js:21:14)
    at Connection.recieveData (/root/cwproj/network/connection.js:35:9)
    at Socket.<anonymous> (/root/cwproj/network/connection.js:13:40)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)`

**Comment by JoshGlazebrook** [comment]
Hmm, which version of node are you using?
